# -*- coding: utf-8 -*-
"""LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDcvQC6JR-ErPqXffAuJIH_kD8CRo-9l
"""

import random

# Convert cell number to grid position
def cell_to_pos(cell):
    return ((cell - 1) // 5, (cell - 1) % 5)

# Convert grid position to cell number
def pos_to_cell(row, col):
    return row * 5 + col + 1


# Display Grid
def display_grid(grid):
    print("\nGrid:")
    for row in grid:
        print(" ".join(row))


# User Input
dirt = list(map(int, input("Enter dirt cells (1-25) separated by space: ").split()))

obstacles = list(map(int, input("Enter obstacle cells (1-25) separated by space: ").split()))


# Create 5x5 environment
grid = [["." for i in range(5)] for j in range(5)]

# Place dirt
for d in dirt:
    r, c = cell_to_pos(d)
    grid[r][c] = "D"

# Place obstacles
for o in obstacles:
    r, c = cell_to_pos(o)
    grid[r][c] = "X"

# Starting point
robot = [0, 0]
grid[0][0] = "R"

display_grid(grid)


# MDP Simulation

actions = [(0,1), (1,0), (0,-1), (-1,0)]
# Right, Down, Left, Up

action_names = ["Right", "Down", "Left", "Up"]

visited_dirt = set()
total_reward = 0


print("\nRobot Navigation:")

for step in range(50):

    r, c = robot
    moved = False

    for i, action in enumerate(actions):

        nr = r + action[0]
        nc = c + action[1]

        if 0 <= nr < 5 and 0 <= nc < 5:

            cell = pos_to_cell(nr,nc)

            # Avoid obstacles
            if cell not in obstacles:

                print("Action:", action_names[i])

                robot = [nr,nc]
                moved = True


                # Collect dirt
                if cell in dirt and cell not in visited_dirt:
                    print("Cleaned dirt at cell", cell)
                    visited_dirt.add(cell)
                    total_reward += 1


                break


    if not moved:
        print("No possible movement")
        break


    if len(visited_dirt) == len(dirt):
        print("\nAll dirt cleaned!")
        break


print("\nFinal Position:", pos_to_cell(robot[0],robot[1]))
print("Total Reward:", total_reward)


# Final Grid
final_grid = [["." for i in range(5)] for j in range(5)]

for d in dirt:
    r,c = cell_to_pos(d)
    final_grid[r][c]="D"

for o in obstacles:
    r,c = cell_to_pos(o)
    final_grid[r][c]="X"

final_grid[robot[0]][robot[1]]="R"

display_grid(final_grid)

import numpy as np

r,c=map(int,input("Enter warehouse size: ").split())
n=r*c

print("Cells:")
for i in range(1,n+1):
    print(i,end=" ")
    if i%c==0: print()

items=list(map(int,input("Items: ").split()))
goal=int(input("Goal: "))
obs=list(map(int,input("Obstacles: ").split()))

V=np.zeros(n+1)
actions=[(-1,0),(1,0),(0,-1),(0,1)]

for _ in range(20):
    old=V.copy()
    for s in range(1,n+1):

        if s==goal:
            V[s]=5
            continue

        val=0
        x,y=(s-1)//c,(s-1)%c

        for dx,dy in actions:
            nx,ny=x+dx,y+dy

            if nx<0 or nx>=r or ny<0 or ny>=c:
                ns=s; reward=-2
            else:
                ns=nx*c+ny+1
                reward=2 if ns in items else 0

                if ns in obs:
                    ns=s
                    reward=-2

            val+=0.25*(reward+0.9*old[ns])

        V[s]=val

print("\nValue Function:")
for i in range(1,n+1):
    print(round(V[i],2),end=" ")
    if i%c==0: print()

import random
import math

# Prices (arms)
prices = [50, 70, 100]

# Actual customer buying probabilities
prob = [0.6, 0.4, 0.2]

rounds = 100


# Epsilon Greedy
def epsilon_greedy():
    count=[0]*3
    reward=[0]*3
    total=0

    for _ in range(rounds):
        if random.random()<0.1:
            a=random.randint(0,2)
        else:
            a=reward.index(max(reward))

        sale=random.random()<prob[a]
        r=prices[a] if sale else 0

        count[a]+=1
        reward[a]+=r
        total+=r

    return total


# UCB
def ucb():
    count=[0]*3
    reward=[0]*3
    total=0

    for t in range(1,rounds+1):

        if t<=3:
            a=t-1
        else:
            ucb_values=[
                reward[i]/count[i]+math.sqrt(2*math.log(t)/count[i])
                for i in range(3)
            ]
            a=ucb_values.index(max(ucb_values))

        sale=random.random()<prob[a]
        r=prices[a] if sale else 0

        count[a]+=1
        reward[a]+=r
        total+=r

    return total


# Thompson Sampling
def thompson():
    success=[1]*3
    fail=[1]*3
    total=0

    for _ in range(rounds):

        samples=[
            random.betavariate(success[i],fail[i])
            for i in range(3)
        ]

        a=samples.index(max(samples))

        sale=random.random()<prob[a]
        r=prices[a] if sale else 0

        if sale:
            success[a]+=1
        else:
            fail[a]+=1

        total+=r

    return total


print("Revenue Comparison")
print("Epsilon Greedy:", epsilon_greedy())
print("UCB:", ucb())
print("Thompson Sampling:", thompson())

import random,math

prices=list(map(int,input("Enter prices: ").split()))
prob=list(map(float,input("Enter buying probabilities: ").split()))
n=int(input("Enter decisions: "))


def run(method):
    c=[0]*len(prices)
    r=[0]*len(prices)
    total=0

    for t in range(1,n+1):
        if method=="E":
            a=random.randrange(len(prices)) if random.random()<0.1 else r.index(max(r))

        elif method=="U":
            a=t-1 if t<=len(prices) else max(range(len(prices)),
            key=lambda i:r[i]/c[i]+math.sqrt(2*math.log(t)/c[i]))

        else:
            a=max(range(len(prices)),
            key=lambda i:random.betavariate(c[i]+1,r[i]+1))

        sale=random.random()<prob[a]
        reward=prices[a] if sale else 0
        c[a]+=1
        r[a]+=reward
        total+=reward

    return total


print("Epsilon Greedy:",run("E"))
print("UCB:",run("U"))
print("Thompson:",run("T"))

import numpy as np

r,c=map(int,input("Grid size: ").split())
n=r*c

print("Cells:")
for i in range(1,n+1):
    print(i,end=" ")
    if i%c==0: print()

goal=int(input("Delivery point: "))
obs=list(map(int,input("Obstacles: ").split()))

V=np.zeros(n+1)
policy=[0]*(n+1)
moves=[(-1,0),(1,0),(0,-1),(0,1)]

for _ in range(20):

    # Policy Evaluation
    for _ in range(10):
        for s in range(1,n+1):
            if s==goal: V[s]=10; continue
            x,y=(s-1)//c,(s-1)%c
            a=policy[s]
            nx,ny=x+moves[a][0],y+moves[a][1]

            if nx<0 or nx>=r or ny<0 or ny>=c or (nx*c+ny+1) in obs:
                V[s]=-1
            else:
                V[s]=-1+0.9*V[nx*c+ny+1]

    # Policy Improvement
    stable=True
    for s in range(1,n+1):
        if s==goal: continue

        old=policy[s]
        vals=[]

        x,y=(s-1)//c,(s-1)%c
        for a in range(4):
            nx,ny=x+moves[a][0],y+moves[a][1]
            if 0<=nx<r and 0<=ny<c and nx*c+ny+1 not in obs:
                vals.append(V[nx*c+ny+1])
            else:
                vals.append(-99)

        policy[s]=np.argmax(vals)

        if old!=policy[s]:
            stable=False

    if stable: break


print("\nOptimal Policy:")
for i in range(1,n+1):
    print(["U","D","L","R"][policy[i]],end=" ")
    if i%c==0: print()

import numpy as np

r,c=map(int,input("Grid size: ").split())
n=r*c

print("Cells:")
for i in range(1,n+1):
    print(i,end=" ")
    if i%c==0: print()

pickup=int(input("Pickup point: "))
obs=list(map(int,input("Obstacles: ").split()))

V=np.zeros(n+1)
moves=[(-1,0),(1,0),(0,-1),(0,1)]
policy=[0]*(n+1)

for _ in range(50):

    old=V.copy()

    for s in range(1,n+1):

        if s==pickup:
            V[s]=10
            continue

        x,y=(s-1)//c,(s-1)%c
        vals=[]

        for dx,dy in moves:
            nx,ny=x+dx,y+dy

            if 0<=nx<r and 0<=ny<c and nx*c+ny+1 not in obs:
                ns=nx*c+ny+1
                vals.append(-1+0.9*old[ns])
            else:
                vals.append(-1)

        V[s]=max(vals)
        policy[s]=np.argmax(vals)


print("\nOptimal Dispatch Policy:")
for i in range(1,n+1):
    print(["U","D","L","R"][policy[i]],end=" ")
    if i%c==0: print()

import random,math

ads=int(input("Number of ads: "))
prob=list(map(float,input("Click probabilities: ").split()))
n=int(input("Number of rounds: "))


def run(method):
    clicks=[0]*ads
    count=[0]*ads
    total=0

    for t in range(1,n+1):

        if method=="E":
            a=random.randrange(ads) if random.random()<0.1 else clicks.index(max(clicks))

        elif method=="U":
            a=t-1 if t<=ads else max(range(ads),
            key=lambda i:clicks[i]/count[i]+math.sqrt(2*math.log(t)/count[i]))

        else:
            a=max(range(ads),
            key=lambda i:random.betavariate(clicks[i]+1,count[i]-clicks[i]+1))


        click=random.random()<prob[a]

        if click:
            clicks[a]+=1
            total+=1

        count[a]+=1

    return total/n


print("\nClick Through Rate:")
print("Epsilon Greedy:",round(run("E"),3))
print("UCB:",round(run("U"),3))
print("Thompson Sampling:",round(run("T"),3))

import numpy as np

r,c=map(int,input("Grid size: ").split())
n=r*c

print("Cells:")
for i in range(1,n+1):
    print(i,end=" ")
    if i%c==0: print()

goal=int(input("Delivery point: "))
obs=list(map(int,input("Obstacles: ").split()))

V=np.zeros(n+1)
moves=[(-1,0),(1,0),(0,-1),(0,1)]

for _ in range(50):
    old=V.copy()

    for s in range(1,n+1):

        if s==goal:
            V[s]=10
            continue

        x,y=(s-1)//c,(s-1)%c
        values=[]

        for dx,dy in moves:
            nx,ny=x+dx,y+dy

            if 0<=nx<r and 0<=ny<c and nx*c+ny+1 not in obs:
                ns=nx*c+ny+1
                values.append(-1+0.9*old[ns])
            else:
                values.append(-1)

        V[s]=max(values)


print("\nState Value Function:")
for i in range(1,n+1):
    print(round(V[i],2),end="\t")
    if i%c==0:
        print()


# Visualization
import matplotlib.pyplot as plt

plt.imshow(V[1:].reshape(r,c),cmap="viridis")
plt.colorbar()
plt.title("Value Function")
plt.show()

import random

r,c=map(int,input("Road size: ").split())
n=r*c

print("Intersections:")
for i in range(1,n+1):
    print(i,end=" ")
    if i%c==0: print()

dest=int(input("Destination: "))
obs=list(map(int,input("Obstacles: ").split()))

pos=1
moves=[(-1,0),(1,0),(0,-1),(0,1)]
names=["UP","DOWN","LEFT","RIGHT"]

steps=0
reward=0

print("\nCar Route:")

while pos!=dest and steps<50:

    x,y=(pos-1)//c,(pos-1)%c
    choices=[]

    for i,(dx,dy) in enumerate(moves):
        nx,ny=x+dx,y+dy

        if 0<=nx<r and 0<=ny<c:
            ns=nx*c+ny+1
            if ns not in obs:
                choices.append((i,ns))

    action,new= random.choice(choices)

    print("Move:",names[action],"->",new)

    pos=new
    reward-=1
    steps+=1


if pos==dest:
    reward+=10
    print("\nDestination reached safely!")
else:
    print("\nFailed to reach destination")

print("Steps:",steps)
print("Total Reward:",reward)

import random

rep=int(input("Number of representatives: "))
calls=int(input("Number of calls: "))

def monte_carlo(policy):
    value=[0]*rep
    count=[0]*rep

    for _ in range(calls):

        if policy=="Random":
            r=random.randint(0,rep-1)

        else:  # Best available policy
            r=value.index(max(value))

        reward=random.randint(1,10)  # customer satisfaction

        count[r]+=1
        value[r]+= (reward-value[r])/count[r]

    return value


print("\nEstimated Value Function:")

print("Random Policy:",monte_carlo("Random"))
print("Best Assignment Policy:",monte_carlo("Best"))

import random

n=int(input("Number of investments: "))
returns=list(map(float,input("Return probabilities: ").split()))
episodes=int(input("Episodes: "))

policy=[1/n]*n
lr=0.1


for _ in range(episodes):

    action=random.choices(range(n),weights=policy)[0]

    reward=random.uniform(-1,1) if random.random()>returns[action] else random.uniform(1,5)

    # Policy Gradient update
    for i in range(n):
        if i==action:
            policy[i]+=lr*reward*(1-policy[i])
        else:
            policy[i]-=lr*reward*policy[i]

    # Normalize
    s=sum(policy)
    policy=[max(0,p/s) for p in policy]


print("\nOptimized Investment Policy:")
for i,p in enumerate(policy):
    print("Investment",i+1,":",round(p,3))

print("Best Investment:",policy.index(max(policy))+1)